name: 'urban_safety'
version: '1.0.0'

profile: 'urban_safety'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  urban_safety:
    staging:
      materialized: view
    intermediate:
      materialized: view
    marts:
      materialized: table